name: Robot Framework Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.201/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Run Robot Framework tests
        run: robot -d results Tests || true

      - name: Upload Robot Framework Report to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: robot-framework-report
          path: results/

      - name: Send Report to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Your Github Actions
          fields: repo,message,commit,author,action,eventName,ref,workflow,took  # Adjust or remove fields based on your preferences
          # If you use outputs from the Robot Framework step, you can format a more detailed message here
          text: Robot Framework Test Results are here! Check the attachment.
          files: results/report.html  # Adjust the path to your Robot Framework report
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
