name: Robot Framework Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.201/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Run Robot Framework tests
        run: |
              robot -d results Tests/LoginTests.robot || true 
              ls -la
              pwd

      - name: Archive Test Reports and Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: robot-reports
          path: results

      - name: Upload Reports to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: C072G3NS0JK
          run: |
          curl -F file=@results/report.html -F "initial_comment=Here is the file we generated" -F channels=$SLACK_CHANNEL -H "Authorization: Bearer $SLACK_TOKEN" https://slack.com/api/files.upload
